#!/usr/bin/perl
use strict;
use warnings;
use FindBin qw($Bin);
use lib ( "$Bin/../lib", "$Bin/../extlib" );
BEGIN {
    my $mtdir = $ENV{MT_HOME} ? "$ENV{MT_HOME}/" : '';
    unshift @INC, "$mtdir$_" foreach qw( lib extlib );
    warn "MT_HOME environment variable not set" unless $ENV{MT_HOME};
}
use MT::Bootstrap::CLI App => 'ThemeManager::Tool::Controller';

__END__

=head1 NAME

tmctl - Command-line tool for interacting with Theme Manager

=head1 VERSION

You can always find the latest version of the plugin code and documentation at:

  http://github.com/openmelody/mt-plugin-theme-manager

=head1 SYNOPSIS

Usage: tmctl [options] COMMAND [ARG, [ARG, [ARG, [...]]]

Options:

  --dryrun     Run through without modifying anything
  --verbose   Output more progress information
  --man       Output the man page for the utility
  --help      Output this message

Example:

  cd /path/to/mt_dir
  export MT_HOME="$(pwd)"
  ./addons/ThemeManager.plugin/tools/tmctl list
  ./addons/ThemeManager.plugin/tools/tmctl upgrade blog 22
  ./addons/ThemeManager.plugin/tools/tmctl upgrade theme my_custom_theme

=head1 DESCRIPTION

For a high-level overview of this plugin and command-line utility, please see:

  http://github.com/endevver/mt-plugin-theme-manager#readme

=head2 IMPORTANT CAVEATS

This is an B<extremely powerful utility> with absolutely no facility for
rollback. Although we believe it to be entirely reliable, even the
developers of this plugin back up their database before running it or any
utility of its kind. If you don't back up your database and it gets hosed
because of a bug or because you accidentally selected the wrong options,
there's really only one person to blame and it's not the creator of this
software.

We also suggest that you use the C<--dryrun> flag first before executing
the utility without it because it serve to provide you with both some
familiarity with the command's actions as well as possible illuminate a
mistake you have made in omitting or including certain flags.

=head1 OPTIONS

The following command-line options are supported by the utility.

=over 4

=item --dryrun

Carries out the actions specified by the flags and arguments provided on
the command line but makes no modifications to the database.

=item --verbose

Output more progress information

=item --man

Output this man-formatted POD documentation.

=item --help

Outputs a short description of the utility's usage

=back

=head1 COMMANDS

=over 4

=item * list

Displays a listing of information about blogs and their themes

=item * upgrade

Upgrades the themes of the specified blog(s). A single blog can be specified
using first form shown in the L<Examples> section:

    tmctl upgrade blog BLOG_ID

All blogs using a particular theme may also be upgraded all at once and in one
step using the second form in the L<Examples> section:

    tmctl upgrade theme TEMPLATE_SET_ID

=back

=head1 DESCRIPTION OF OPERATION

During execution, this utility does DESCRIPTION:

=head1 DEPENDENCIES

=over 4

=item * Log4MT plugin - http://github.com/endevver/mt-plugin-log4mt

Used for general purpose logging and recording of entry permalink redirects

=item * CLITool - http://github.com/endevver/mt-util-clitool

Underlying framework for all of Endevver's command-line interface (CLI) tools

=back

=head1 INCOMPATIBILITIES

No known incompatibilities.

=head1 BUGS AND LIMITATIONS

There are no known bugs in this module.

If you are having problems installing or using the plugin, please check out 
our general knowledge base and help ticket system:

  http://help.endevver.com

=head1 FUTURE FEATURES

The following modes are possible candidates for inclusion in a future version
of this utility.

    tmctl upgrade blog 23,25,32
    tmctl upgrade blog "23 25 32"
    tmctl upgrade blog 1-20
    tmctl list theme my_custom_theme
    tmctl info theme my_custom_theme
    tmctl republish theme my_custom_theme
    tmctl info blog 22
    tmctl check blog 22
    tmctl republish blog 22

=head1 COPYRIGHT

Copyright 2011, Endevver, LLC. All rights reserved.

=head1 LICENSE

This plugin is licensed under the GPL v2.

=head1 ABOUT ENDEVVER

We design and develop web sites, products and services with a focus on 
simplicity, sound design, ease of use and community. We specialize in 
Movable Type and offer numerous services and packages to help customers 
make the most of this powerful publishing platform.

http://endevver.com/

