#!/usr/bin/perl
use strict;
use warnings;
use FindBin qw($Bin);
use lib ( "$Bin/../lib", "$Bin/../extlib" );
BEGIN {
    my $mtdir = $ENV{MT_HOME} ? "$ENV{MT_HOME}/" : '';
    unshift @INC, "$mtdir$_" foreach qw( lib extlib );
}
use MT::Bootstrap::CLI App => 'ThemeManager::Tool::Controller';

__END__

=head1 NAME

tmctl - Command-line tool for interacting with Theme Manager

=head1 VERSION

You can always find the latest version of the plugin code and documentation at:

  http://github.com/openmelody/mt-plugin-theme-manager

=head1 SYNOPSIS

Usage: tmctl [options] COMMAND [ARG, [ARG, [ARG, [...]]]

Options:

  --dryrun     Run through without modifying anything
  --verbose   Output more progress information
  --man       Output the man page for the utility
  --help      Output this message

Example:

  cd /path/to/mt_dir
  export MT_HOME="$(pwd)"
  ./addons/ThemeManager.plugin/tools/tmctl list
  ./addons/ThemeManager.plugin/tools/tmctl upgrade blog 22
  ./addons/ThemeManager.plugin/tools/tmctl upgrade theme my_custom_theme
  ########### NOT YET IMPLEMENTED ############
  # ./addons/ThemeManager.plugin/tools/tmctl list theme my_custom_theme
  # ./addons/ThemeManager.plugin/tools/tmctl info theme my_custom_theme
  # ./addons/ThemeManager.plugin/tools/tmctl republish theme my_custom_theme
  # ./addons/ThemeManager.plugin/tools/tmctl info blog 22
  # ./addons/ThemeManager.plugin/tools/tmctl check blog 22
  # ./addons/ThemeManager.plugin/tools/tmctl republish blog 22
  ############################################

=head1 DESCRIPTION

For a high-level overview of this plugin and command-line utility, please see:

  http://github.com/endevver/mt-plugin-theme-manager#readme

=head2 IMPORTANT CAVEATS

This is an B<extremely powerful utility> with absolutely no facility for
rollback. Although we believe it to be entirely reliable, even the
developers of this plugin back up their database before running it or any
utility of its kind. If you don't back up your database and it gets hosed
because of a bug or because you accidentally selected the wrong options,
there's really only one person to blame and it's not the creator of this
software.

We also suggest that you use the C<--dryrun> flag first before executing
the utility without it because it serve to provide you with both some
familiarity with the command's actions as well as possible illuminate a
mistake you have made in omitting or including certain flags.

=head1 OPTIONS

The following command-line options are supported by the utility.

=over 4

=item --dryrun

Carries out the actions specified by the flags and arguments provided on
the command line but makes no modifications to the database.

=item --force

Normally, the utility will output exactly what it's about to do and then
prompt you for confirmation that you want to continue.  The C<--force>
flag skips this confirmation and simply performs the action specified
by the provided flags and arguments.

=item --verbose

Output more progress information

=item --man

Output this man-formatted POD documentation.

=item --help

Outputs a short description of the utility's usage

=back

=head1 COMMANDS

=over 4

=item * list

=item * info

=item * check

=item * upgrade

=back

=head1 DESCRIPTION OF OPERATION

During execution, this utility does DESCRIPTION:

=head1 DEPENDENCIES

=over 4

=item * Log4MT plugin - http://github.com/endevver/mt-plugin-log4mt

Used for general purpose logging and recording of entry permalink redirects

=item * CLITool - http://github.com/endevver/mt-util-clitool

Underlying framework for all of Endevver's command-line interface (CLI) tools

=back

=head1 INCOMPATIBILITIES

No known incompatibilities.

=head1 BUGS AND LIMITATIONS

There are no known bugs in this module.

If you are having problems installing or using the plugin, please check out 
our general knowledge base and help ticket system:

  http://help.endevver.com

=head1 COPYRIGHT

Copyright 2011, Endevver, LLC. All rights reserved.

=head1 LICENSE

This plugin is licensed under the GPL v2.

=head1 ABOUT ENDEVVER

We design and develop web sites, products and services with a focus on 
simplicity, sound design, ease of use and community. We specialize in 
Movable Type and offer numerous services and packages to help customers 
make the most of this powerful publishing platform.

http://endevver.com/

